  title: boiler
  icon: fas:shower
  path: Boiler
  cards:
    - type: vertical-stack
      cards:
        - type: custom:decluttering-card
          template: title
          variables:
            - name: לוח זמנים לבוילר
    - type: vertical-stack
      cards:
        - type: entities
          show_header_toggle: false
          entities:
          #- switch.broadlink_switch
          - automation.boiler_on
          - entity: input_datetime.boiler_start_time
            #secondary_info: last-changed
            secondary_info: '[[ if(sun.sun.attributes.elevation < 0, "Below", "Above") ]] the horizon'
          - automation.boiler_off
          - entity: input_datetime.boiler_end_time
            secondary_info: last-changed
        - type: vertical-stack
          cards:
            - type: custom:decluttering-card
              template: title
              variables:
                - name: מידע אודות הבוילר
        - type: vertical-stack
          cards:
            - type: entities
              show_header_toggle: false
              entities:
              #- automation.timer_boiler1_off
              #- automation.boiler_with_timer
              #- input_number.slider_boiler
              - entity: sensor.switcher_webapi_state_1
                name: מצב הדוד
              - entity: sensor.switcher_webapi_power_consumption
              - entity: sensor.switcher_webapi_electric_current
              - entity: sensor.switcher_webapi_time_left
                name: זמן לכיבוי
              - entity: sensor.boiler_temp
                name: טמפ׳ הדוד
    - type: vertical-stack
      cards:
        - type: custom:decluttering-card
          template: title
          variables:
            - name: טיימרים קבועים מראש
        - type: horizontal-stack
          cards:
            - type: "custom:button-card"
              entity: script.switcher_turn_on_timer_script_30
              name: "טיימר 30 דק"
              tap_action: 
                action: toggle
              icon: mdi:shower-head
              #color: rgb(0, 255, 0)
              #color_off: rgb(255, 0, 0, 0)
              show_state: true
              size: 80%
              styles:
                card:
                  - height: 80px
                  - text-transform: none
                  #- color: black
                  - background-color: rgb(0 255, 0, 0.5)
                  - font-size: 14px
            - type: "custom:button-card"
              entity: script.switcher_turn_on_timer_script_45
              name: "טיימר 45 דק"
              tap_action: 
                action: toggle
              icon: mdi:shower-head
              #color: rgb(0, 255, 0)
              #color_off: rgb(255, 0, 0, 0)
              show_state: true
              size: 80%
              styles:
                card:
                  - height: 80px
                  - text-transform: none
                  #- color: black
                  - background-color: rgb(0 255, 0, 0.5)
                  - font-size: 14px
            - type: "custom:button-card"
              entity: script.switcher_turn_on_timer_script_60
              name: "טיימר 60 דק"
              icon: mdi:shower-head
              tap_action: 
                action: toggle
              #color: rgb(0, 255, 0)
              #color_off: rgb(255, 0, 0, 0)
              show_state: true
              size: 80%
              styles:
                card:
                  - height: 80px
                  - text-transform: none
                  #- color: black
                  - background-color: rgb(0 255, 0, 0.5)
                  - font-size: 14px
                  
        - type: vertical-stack
          cards:
            - type: custom:decluttering-card
              template: title
              variables:
                - name: פאנל שליטה בבוילר
            - type: horizontal-stack
              cards:
                - type: custom:decluttering-card
                  template: boiler
                  variables:
                    - image: /local/shower.jpg
                    - entity: switcher_webapi
                    - tap_action: toggle
                    - top: 12%
                    - left: 50%
                    - top1: 60%
                    - left1: 50%
                    - direction: rtl
                    - icon: shower-head
                    - text_size: 20
                    - icon_size: 40
                    - text_color: white
                    - icon_color: white
                    - name: boiler